import '../models/bengkel.dart';
import '../models/jasa.dart';
import '../models/service_request.dart';
import '../models/sparepart.dart';
import '../models/vehicle.dart';

List<Vehicle> seedVehicles() => [
  Vehicle(
    id: 'v1',
    nama: 'Honda Vario 160',
    merk: 'Honda',
    plat: 'B 3021 KXY',
    tahun: 2022,
    warna: 'Hitam Doff',
    tipe: 'Matic',
    cc: 157,
    km: 18450,
    maint: [
      MaintItem(
        nama: 'Ganti Oli Mesin',
        intervalKm: 3000,
        intervalBulan: 3,
        lastKm: 15900,
        lastLabel: 'Jun 2026',
      ),
      MaintItem(
        nama: 'Kampas Rem Depan',
        intervalKm: 6000,
        intervalBulan: 12,
        lastKm: 12000,
        lastLabel: 'Feb 2026',
      ),
      MaintItem(
        nama: 'Ganti Oli Gardan',
        intervalKm: 8000,
        intervalBulan: 8,
        lastKm: 12000,
        lastLabel: 'Feb 2026',
      ),
      MaintItem(
        nama: 'Filter Udara',
        intervalKm: 4000,
        intervalBulan: 6,
        lastKm: 16000,
        lastLabel: 'Apr 2026',
      ),
      MaintItem(
        nama: 'Busi',
        intervalKm: 8000,
        intervalBulan: 12,
        lastKm: 12000,
        lastLabel: 'Feb 2026',
      ),
      MaintItem(
        nama: 'V-Belt & Roller CVT',
        intervalKm: 24000,
        intervalBulan: 24,
        lastKm: 0,
        lastLabel: '—',
      ),
    ],
  ),
  Vehicle(
    id: 'v2',
    nama: 'Yamaha NMAX 155',
    merk: 'Yamaha',
    plat: 'B 6654 TRA',
    tahun: 2021,
    warna: 'Biru Metalik',
    tipe: 'Matic',
    cc: 155,
    km: 32100,
    maint: [
      MaintItem(
        nama: 'Ganti Oli Mesin',
        intervalKm: 3000,
        intervalBulan: 3,
        lastKm: 30000,
        lastLabel: 'Mei 2026',
      ),
      MaintItem(
        nama: 'V-Belt & Roller CVT',
        intervalKm: 24000,
        intervalBulan: 24,
        lastKm: 8000,
        lastLabel: '2024',
      ),
      MaintItem(
        nama: 'Kampas Rem Depan',
        intervalKm: 6000,
        intervalBulan: 12,
        lastKm: 30000,
        lastLabel: 'Mei 2026',
      ),
      MaintItem(
        nama: 'Filter Udara',
        intervalKm: 4000,
        intervalBulan: 6,
        lastKm: 30000,
        lastLabel: 'Mei 2026',
      ),
    ],
  ),
];

List<Bengkel> seedBengkels() => [
  Bengkel(
    id: 'b1',
    nama: 'Jaya Motor',
    alamat: 'Jl. Merdeka No. 12, Jakarta Selatan',
    rating: 4.8,
    ulasan: 212,
    jarak: '1,2 km',
    jam: '08.00 – 17.00',
    buka: true,
    spesialis: 'Spesialis Motor Matic & Bebek',
    verified: true,
  ),
  Bengkel(
    id: 'b2',
    nama: 'AHASS Sentosa Motor',
    alamat: 'Jl. Sudirman No. 40, Jakarta',
    rating: 4.6,
    ulasan: 98,
    jarak: '3,0 km',
    jam: '08.00 – 16.00',
    buka: true,
    spesialis: 'Bengkel Resmi Honda',
    verified: true,
  ),
  Bengkel(
    id: 'b3',
    nama: 'Sinar Abadi Racing',
    alamat: 'Jl. Fatmawati No. 7, Jakarta',
    rating: 4.5,
    ulasan: 54,
    jarak: '4,8 km',
    jam: '09.00 – 20.00',
    buka: false,
    spesialis: 'Modifikasi & Bore Up',
    verified: false,
  ),
];

List<Sparepart> seedSpareparts() => [
  Sparepart(
    id: 'p1',
    nama: 'Oli Mesin AHM MPX2 (0,8L)',
    kategori: 'Oli & Cairan',
    harga: 55000,
    stok: 24,
  ),
  Sparepart(
    id: 'p2',
    nama: 'Kampas Rem Depan',
    kategori: 'Pengereman',
    harga: 85000,
    stok: 12,
  ),
  Sparepart(
    id: 'p3',
    nama: 'Busi NGK CPR9EA',
    kategori: 'Kelistrikan',
    harga: 28000,
    stok: 40,
  ),
  Sparepart(
    id: 'p4',
    nama: 'Aki GS GTZ5S',
    kategori: 'Kelistrikan',
    harga: 220000,
    stok: 6,
  ),
  Sparepart(
    id: 'p5',
    nama: 'Ban Belakang IRC 100/80-14',
    kategori: 'Ban',
    harga: 235000,
    stok: 8,
  ),
  Sparepart(
    id: 'p6',
    nama: 'V-Belt Set Original',
    kategori: 'CVT',
    harga: 165000,
    stok: 10,
  ),
  Sparepart(
    id: 'p7',
    nama: 'Roller CVT Set',
    kategori: 'CVT',
    harga: 90000,
    stok: 15,
  ),
  Sparepart(
    id: 'p8',
    nama: 'Filter Udara',
    kategori: 'Filter',
    harga: 45000,
    stok: 3,
  ),
];

List<Jasa> seedJasa() => [
  Jasa(id: 'j1', nama: 'Jasa Servis Rutin', harga: 90000),
  Jasa(id: 'j2', nama: 'Jasa Ganti Oli', harga: 25000),
  Jasa(id: 'j3', nama: 'Jasa Ganti Kampas Rem', harga: 50000),
  Jasa(id: 'j4', nama: 'Jasa Bongkar CVT', harga: 65000),
  Jasa(id: 'j5', nama: 'Jasa Tune Up Mesin', harga: 100000),
  Jasa(id: 'j6', nama: 'Jasa Ganti Ban', harga: 30000),
  Jasa(id: 'j7', nama: 'Jasa Servis Injeksi/Karburator', harga: 75000),
  Jasa(id: 'j8', nama: 'Jasa Ganti Aki', harga: 20000),
];

List<ServiceRequest> seedServiceRequests() => [
  ServiceRequest(
    id: 'SVC-2065',
    customer: 'Andi Pratama',
    mine: true,
    vehId: 'v1',
    vehLabel: 'Honda Vario 160 · B 3021 KXY',
    bengkelId: 'b1',
    tanggal: DateTime(2026, 7, 5),
    jam: '09.00',
    jenis: 'Servis Rutin + Ganti Oli',
    status: ServiceStatus.dikerjakan,
    keluhan: 'Servis rutin, tarikan terasa berat di putaran atas.',
    biaya: 0,
  ),
  ServiceRequest(
    id: 'SVC-2071',
    customer: 'Budi Santoso',
    mine: false,
    vehLabel: 'Honda BeAT Street · B 1122 CDX',
    bengkelId: 'b1',
    tanggal: DateTime(2026, 7, 5),
    jam: '11.00',
    jenis: 'Ganti Ban Belakang',
    status: ServiceStatus.menunggu,
    keluhan: 'Ban belakang sudah gundul dan sering selip saat hujan.',
    biaya: 0,
  ),
  ServiceRequest(
    id: 'SVC-2068',
    customer: 'Citra Dewi',
    mine: false,
    vehLabel: 'Yamaha NMAX · B 4419 QW',
    bengkelId: 'b1',
    tanggal: DateTime(2026, 7, 5),
    jam: '13.30',
    jenis: 'Perbaikan Rem Depan',
    status: ServiceStatus.dikonfirmasi,
    keluhan: 'Rem depan bunyi mencicit saat ditekan.',
    biaya: 0,
  ),
  ServiceRequest(
    id: 'SVC-2041',
    customer: 'Andi Pratama',
    mine: true,
    vehId: 'v1',
    vehLabel: 'Honda Vario 160 · B 3021 KXY',
    bengkelId: 'b1',
    tanggal: DateTime(2026, 6, 12),
    jam: '10.00',
    jenis: 'Servis Rutin + Ganti Oli',
    status: ServiceStatus.selesai,
    keluhan: 'Servis rutin bulanan.',
    biaya: 145000,
    items: const [
      ServiceItem(nama: 'Oli Mesin AHM MPX2', qty: 1, harga: 55000),
      ServiceItem(nama: 'Jasa Servis Rutin', qty: 1, harga: 90000),
    ],
    saran:
        'Kampas rem depan mulai menipis — disarankan ganti dalam ~2 bulan atau sebelum menyentuh 21.000 km. Cek tekanan angin ban setiap 2 minggu.',
    saranBulan: 'Agustus 2026',
  ),
  ServiceRequest(
    id: 'SVC-1987',
    customer: 'Andi Pratama',
    mine: true,
    vehId: 'v2',
    vehLabel: 'Yamaha NMAX 155 · B 6654 TRA',
    bengkelId: 'b1',
    tanggal: DateTime(2026, 5, 3),
    jam: '14.00',
    jenis: 'Ganti V-Belt & Roller CVT',
    status: ServiceStatus.selesai,
    keluhan: 'Muncul bunyi kasar dari area CVT.',
    biaya: 320000,
    items: const [
      ServiceItem(nama: 'V-Belt Set Original', qty: 1, harga: 165000),
      ServiceItem(nama: 'Roller CVT Set', qty: 1, harga: 90000),
      ServiceItem(nama: 'Jasa Bongkar CVT', qty: 1, harga: 65000),
    ],
    saran:
        'Kondisi CVT kembali normal. Servis CVT berikutnya diperkirakan di ~56.000 km.',
    saranBulan: '—',
  ),
];
